============================= test session starts =============================
platform win32 -- Python 3.12.2, pytest-8.1.1, pluggy-1.5.0
rootdir: C:\Users\DELL\Documents
collected 1 item / 3 errors

=================================== ERRORS ====================================
__________________________ ERROR collecting My Music __________________________
..\AppData\Local\Programs\Python\Python312\Lib\site-packages\_pytest\runner.py:340: in from_call
    result: Optional[TResult] = func()
..\AppData\Local\Programs\Python\Python312\Lib\site-packages\_pytest\runner.py:388: in collect
    return list(collector.collect())
..\AppData\Local\Programs\Python\Python312\Lib\site-packages\_pytest\main.py:523: in collect
    for direntry in scandir(self.path):
..\AppData\Local\Programs\Python\Python312\Lib\site-packages\_pytest\pathlib.py:812: in scandir
    with os.scandir(path) as s:
E   PermissionError: [WinError 5] Access is denied: 'C:\\Users\\DELL\\Documents\\My Music'
________________________ ERROR collecting My Pictures _________________________
..\AppData\Local\Programs\Python\Python312\Lib\site-packages\_pytest\runner.py:340: in from_call
    result: Optional[TResult] = func()
..\AppData\Local\Programs\Python\Python312\Lib\site-packages\_pytest\runner.py:388: in collect
    return list(collector.collect())
..\AppData\Local\Programs\Python\Python312\Lib\site-packages\_pytest\main.py:523: in collect
    for direntry in scandir(self.path):
..\AppData\Local\Programs\Python\Python312\Lib\site-packages\_pytest\pathlib.py:812: in scandir
    with os.scandir(path) as s:
E   PermissionError: [WinError 5] Access is denied: 'C:\\Users\\DELL\\Documents\\My Pictures'
_________________________ ERROR collecting My Videos __________________________
..\AppData\Local\Programs\Python\Python312\Lib\site-packages\_pytest\runner.py:340: in from_call
    result: Optional[TResult] = func()
..\AppData\Local\Programs\Python\Python312\Lib\site-packages\_pytest\runner.py:388: in collect
    return list(collector.collect())
..\AppData\Local\Programs\Python\Python312\Lib\site-packages\_pytest\main.py:523: in collect
    for direntry in scandir(self.path):
..\AppData\Local\Programs\Python\Python312\Lib\site-packages\_pytest\pathlib.py:812: in scandir
    with os.scandir(path) as s:
E   PermissionError: [WinError 5] Access is denied: 'C:\\Users\\DELL\\Documents\\My Videos'
=========================== short test summary info ===========================
ERROR My Music - PermissionError: [WinError 5] Access is denied: 'C:\\Users\\...
ERROR My Pictures - PermissionError: [WinError 5] Access is denied: 'C:\\User...
ERROR My Videos - PermissionError: [WinError 5] Access is denied: 'C:\\Users\...
!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!
============================== 3 errors in 0.90s ==============================
